name: CI

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:

jobs:
  format:
    runs-on: ubuntu-20.04

    steps:
      - uses: dtolnay/rust-toolchain@stable

      - uses: actions/checkout@v1

      - name: Rustfmt check
        run: cargo fmt --check

  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Install Xen headers and libraries
        run: sudo apt-get install -y libxen-dev

      - uses: dtolnay/rust-toolchain@stable
      - uses: actions/checkout@v1

      - name: Build crate with clippy warnings
        run: cargo clippy

  publish:
    needs: [format, build]
    runs-on: ubuntu-20.04
    
    # publish on crates.io
    # only if push on master, and tag is 'v*'
    # this should be triggered by cargo release, which creates a new tag and pushes to the repo
    # cargo release --no-dev-version --skip-publish minor
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Install Xen headers and libraries
        run: sudo apt-get install -y libxen-dev

      - uses: actions/checkout@v1
        
      - uses: dtolnay/rust-toolchain@stable

      - name: Publish
        shell: bash
        run: |
          cargo publish --token ${{ secrets.CRATES_TOKEN }}
